/*
  Isar todo model
  Converts todo model in to Isar todo model to store in Isar DB
 */

import 'package:do_it/features/todo/domain/models/todo.dart';
import 'package:flutter/foundation.dart';
import 'package:isar/isar.dart';

// -------------------------------------------------
// SubTask (embedded inside Task)
// -------------------------------------------------
part 'Isar_todo.g.dart'; // <-- generated by build_runner

@embedded
class IsarSubTask {
  IsarSubTask();
  late String id;
  late String title;
  late String description;
  bool isCompleted = false;

  // -------------------------------------------------
  // Helper: convert to/from domain model
  // -------------------------------------------------
  SubTask toDomain() => SubTask(id: id, title: title, description: description);

  factory IsarSubTask.fromDomain(SubTask sub) =>
      IsarSubTask()
        ..id = sub.id
        ..title = sub.title
        ..description = sub.description
        ..isCompleted = sub.isCompleted;
}

class IsarTask {
  IsarTask();
  Id isarId = Isar.autoIncrement;
  late String id;
  late String title;
  late String description;
  late bool isCompleted;
  @Index(type: IndexType.value)
  List<String> tags = const [];
  int? startTime;
  int? endTime;
  double progress = 0.0;
  int? reminderTime;

  final subTasks = IsarLinks<IsarSubTask>();

  // -------------------------------------------------
  // Domain to Isar/Isar to Domain conversion
  // -------------------------------------------------
  Task toDOmain() {
    final List<SubTask> domainSubs =
        subTasks.map((subtask) => subtask.toDomain()).toList();
    return Task(
      id: id,
      title: title,
      description: description,
      isCompleted: isCompleted,
      tags: tags,
      startTime:
          startTime != null
              ? DateTime.fromMillisecondsSinceEpoch(startTime!)
              : null,
      endTime:
          endTime != null
              ? DateTime.fromMillisecondsSinceEpoch(endTime!)
              : null,
      progress: progress,
      reminderTime:
          reminderTime != null
              ? DateTime.fromMillisecondsSinceEpoch(reminderTime!)
              : null,
      subTasks: domainSubs,
    );
  }

  factory IsarTask.fromDomain(Task task) {
    final isar =
        IsarTask()
          ..title = task.title
          ..description = task.description
          ..isCompleted = task.isCompleted
          ..tags = task.tags
          ..startTime = task.startTime?.millisecondsSinceEpoch
          ..endTime = task.endTime?.millisecondsSinceEpoch
          ..progress = task.progress
          ..reminderTime = task.reminderTime?.millisecondsSinceEpoch;
    for (final sub in task.subTasks) {
      isar.subTasks.add(IsarSubTask.fromDomain(sub));
    }
    return isar;
  }
}
