/*
  Isar todo model
  Converts todo model in to Isar todo model to store in Isar DB
 */

import 'package:do_it/features/todo/domain/models/todo.dart';
import 'package:flutter/foundation.dart';
import 'package:isar/isar.dart';

// -------------------------------------------------
// SubTask (embedded inside Task)
// -------------------------------------------------
//part 'isar_models.g.dart'; // <-- generated by build_runner

@embedded
class IsarSubTask {
  IsarSubTask();
  late String id;
  late String title;
  late String description;
  bool isCompleted = false;

  // -------------------------------------------------
  // Helper: convert to/from domain model
  // -------------------------------------------------
  SubTask toDomain() => SubTask(id: id, title: title, description: description);

  factory IsarSubTask.fromDomain(SubTask sub) =>
      IsarSubTask()
        ..id = sub.id
        ..title = sub.title
        ..description = sub.description
        ..isCompleted = sub.isCompleted;
}

class IsarTodo {
  Id isard = Isar.autoIncrement;
  late String id;
  late String title;
  late String description;
  late bool isCompleted;
  @Index(type: IndexType.value)
  List<String> tags = const [];
  int? startTime;
  int? endTime;
  double progress = 0.0;
  int? reminderTime;

  final subTasks = IsarLinks<IsarSubTask>();
}
